parameters:

services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    app.scheduler:
        class: AppBundle\Service\Scheduler
        arguments: [@doctrine.orm.entity_manager]

    app.mandrill:
        class: Mandrill
        arguments: [%mandrill_api_key%]

    app.sale.mailer:
        class: AppBundle\Service\SaleMailer
        arguments:
            - @app.mandrill
            - %vendor_email%
            - %base_url%

    app.service.mailchimp:
        class: AppBundle\Service\MailChimp
        arguments:
            - %mailchimp_api_key%
            - %mailchimp_addon_list_map%
            - %mailchimp_api_dc%
            - %mailchimp_enabled%