parameters:

services:
    app.scheduler:
        class: AppBundle\Service\Scheduler
        arguments: [@doctrine.orm.entity_manager]

    app.mandrill:
        class: Mandrill
        arguments: [%mandrill_api_key%]